<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MAVSMVC.Application\MAVSMVC.Application.csproj" />
    <ProjectReference Include="..\MAVSMVC.Domain\MAVSMVC.Domain.csproj" />
    <ProjectReference Include="..\MAVSMVC.Infraestructure\MAVSMVC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
